Display the user, created date, and updated date when running --status command.
- Use ETLJobDTO and UserDTO instead of ETLJob and User from mt-api. (User seems to bring in many NoClassDefFoundErrors)
- Bump mt-api dependency to 0.375 for ETLJob anyway.